services:
  web:
    build: .
    container_name: hyperlog-website
    env_file:
      - .env
    networks:
      - hyperlog_prod
    restart: unless-stopped

networks:
  hyperlog_prod:
    external: true
