# HyperLog Website - hyperlog.aero

server {
    listen 80;
    listen [::]:80;
    server_name hyperlog.aero www.hyperlog.aero;
    location /.well-known/acme-challenge/ { root /var/lib/letsencrypt; }
    location / { return 301 https://hyperlog.aero$request_uri; }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name hyperlog.aero www.hyperlog.aero;

    ssl_certificate /etc/letsencrypt/live/hyperlog.aero/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hyperlog.aero/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    location / {
        proxy_pass http://hyperlog-website:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
